### PR TITLE
fix: compatibility with ocp 4.2

### PR DESCRIPTION
**Pull request by psturc**
### Notes
This PR is WIP since requested `OCP 4.2 beta` from RHPDS does not contain `postgresql v9.5` which is required by SSO. So in order to finish installation of mobile services, one must modify sso-postgresql DC to request `postgresql v9.6` during the installation.

I'll wait until `4.2 GA` is available on RHPDS and try again.

### Verification steps
1. Request OCP 4.2 cluster
2. `oc login` to it and run the installer

**Update**: Actually I think it's ready to be reviewed and merged now so we can get rid of dependency on service catalog.
If the postgresql version is still a problem, we can create a follow-up issue later.

(ping me if you need ocp 4.2 for verification)

### CODE REVIEW

**Comment by b1zzu** [comment]
:eyes:

**Comment by b1zzu** [comment]
@psturc How did you fix the CORS issues?
image

**Comment by psturc** [comment]
> @psturc How did you fix the CORS issues?
> image

Sorry, I followed the guide from docs: https://docs.openshift.com/container-platform/4.2/authentication/allowing-javascript-access-api-server.html#auth-allowing-javascript-access-api-server_auth-allowed-origins

After you save the changes, you have to wait for couple of minutes before the changes are applied

**Comment by b1zzu** [comment]
@psturc it works, thanks

**Comment by b1zzu** [comment]
I like the fact that in ocp4.2 to do this kind of operation you don't have to edit the master-config.yml

**Review by b1zzu — APPROVED** [review]
LGTM

**Pull request merged**
